# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 65a36cda1521f3331de684083e78640d12d5fd0aad59d32d4fe9c0d7068d7bfd7ac81a1cb1a70f8cc7c9fdab03dffa01ccacd98c5d8b5976832a722010c928c5

test:
  secret_key_base: 347cae76ef684e1c74cd8af1fee66daea96eb6a164981e4d6fa9cb7866c2f699a9958a82252472c1dd1a1ea422380df1e0d1aa07f0fd400e7365a9be627711fc

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
